### PR TITLE
Reducing the number of the test data. Sampling instead of %100 test

### PR DESCRIPTION
**Pull request by blondeholly**

### CODE REVIEW

**Review by danielchildsbjss — DISMISSED** [review]
I'm a fan of this change, this is much more maintainable

**Comment by blondeholly** [comment]
I also approve this :) I have looked at the Jenkins runs and looks great, great work Zeynep. Can't approve it because I opened the PR. Sorry didn't think of that. In order to get the amount of reviewers though I asked Dan Childs to have a look and he is happy and has approved, so when Iulia is in and has looked it over as well hopefully we can get it in.

**Review by IuliaDVSA — APPROVED** [review]
VTA-401 Reviewed and approved

**Review by danielchildsbjss — APPROVED** [review]

**Comment by ZeypEr** [comment]
VTA-401 401 has been reviewed and approved.

**Pull request merged**
