### PR TITLE
Evaluating the tests which have "ignore tags". Deleting some unnecessary of them and creating another ticket for the rest of it.

### PR DESCRIPTION
**Pull request by ZeypEr**
giving comment status to some of the ignore tags to activate these tests in test suite

### CODE REVIEW

**Review by Ian-Hodges — COMMENTED** [review]
Any reason why the lines are commented out rather than removed completely?

**Comment by ZeypEr** [comment]
Because the test suite is not a simple small suite. Keeping those tags in there will save a huge time while I need to find them back again. That's why I would like to keep it for a while

**Review by Ian-Hodges — DISMISSED** [review]

**Review by blondeholly — DISMISSED** [review]

**Comment by ZeypEr** [comment]
Removed 8 all classes with ignoring tag tests from the BE suite:

1- Ignore("This is just an example of how to read json data from external file and insert it in a specific table using AWS SDK")-TEST FAILED 1 OF 1 public class InsertTestResultsInDynamo {
2- Ignore("This is just an example of how to read json data from external file and insert it in a specific table using AWS SDK")-TEST FAILED 1 OF 1 ("[CVSB-11991](https://jira.dvsacloud.uk/browse/CVSB-11991) - Insert previous test-results into DynamoDB using Java AWS sdk")
3- Ignore("This is just an example of how to read json data from external file and insert it in a specific table using AWS SDK")-TEST FAILED 1 OF 1 Title("[CVSB-12181](https://jira.dvsacloud.uk/browse/CVSB-12181) - Delete entries fro activities table in DynamoDB using Java AWS sdk")
4- Ignore("This is just an example of how to update test station email address insert it in a specific table using AWS SDK")-TEST FAILED 1 OF 1 ( Title( "[CVSB-10530](https://jira.dvsacloud.uk/browse/CVSB-10530)- Update entry from test-stations table in DynamoDB using Java AWS sdk")
5- Ignore("This is just an example of how to get the next systemNumber to be generated from the backend")-TEST FAIED 1OF 1 Title("[CVSB-10598](https://jira.dvsacloud.uk/browse/CVSB-10598) - Get next systemNumber in sequence")
6- Ignore("This is just an example of how to get the next trailerId to be generated from the backend")-TEST FAILED 1OF 1 Title("[CVSB-10131](https://jira.dvsacloud.uk/browse/CVSB-10131) - Get next trailerId in sequence")
7- Ignore("Remove the ignore annotation when the updates on tech record will be enabled for vehicles without adr details")6 FAILED, 34 PASSED
8- Ignore("Test dropped out until duplicate-vin issue is dealt with")failed 2, passed 12 Title("[CVSB-417](https://jira.dvsacloud.uk/browse/CVSB-417) - [CVSB-949](https://jira.dvsacloud.uk/browse/CVSB-949) - [CVSB-1140](https://jira.dvsacloud.uk/browse/CVSB-1140) / [CVSB-3505](https://jira.dvsacloud.uk/browse/CVSB-3505) - API Consumer tries to create a new test result for submitted/canceled with missing property - additionalInformation")([CVSB-9010](https://jira.dvsacloud.uk/browse/CVSB-9010) closed

 And removed all outdated classes from the BE suite:

 1- Ignore("outdated vtm test") Title("[CVSB-417](https://jira.dvsacloud.uk/browse/CVSB-417) - [CVSB-949](https://jira.dvsacloud.uk/browse/CVSB-949) - [CVSB-1140](https://jira.dvsacloud.uk/browse/CVSB-1140) / [CVSB-3505](https://jira.dvsacloud.uk/browse/CVSB-3505) - API Consumer tries to create a new test result for submitted/canceled with missing property - additionalInformation")([CVSB-9010](https://jira.dvsacloud.uk/browse/CVSB-9010) closed

2- Ignore("outdated vtm test") Title("[CVSB-417](https://jira.dvsacloud.uk/browse/CVSB-417) - [CVSB-949](https://jira.dvsacloud.uk/browse/CVSB-949) - [CVSB-1140](https://jira.dvsacloud.uk/browse/CVSB-1140) / [CVSB-3505](https://jira.dvsacloud.uk/browse/CVSB-3505) - API Consumer tries to create a new test result for submitted/canceled with missing property - additionalInformation")([CVSB-9010](https://jira.dvsacloud.uk/browse/CVSB-9010) closed

3- Ignore("outdated vtm test") Title("[CVSB-417](https://jira.dvsacloud.uk/browse/CVSB-417) - [CVSB-949](https://jira.dvsacloud.uk/browse/CVSB-949) - [CVSB-1140](https://jira.dvsacloud.uk/browse/CVSB-1140) / [CVSB-3505](https://jira.dvsacloud.uk/browse/CVSB-3505) - API Consumer tries to create a new test result for submitted/canceled with missing property - additionalInformation")([CVSB-9010](https://jira.dvsacloud.uk/browse/CVSB-9010) closed

4- Ignore("outdated vtm test") Title("[CVSB-417](https://jira.dvsacloud.uk/browse/CVSB-417) - [CVSB-949](https://jira.dvsacloud.uk/browse/CVSB-949) - [CVSB-1140](https://jira.dvsacloud.uk/browse/CVSB-1140) / [CVSB-3505](https://jira.dvsacloud.uk/browse/CVSB-3505) - API Consumer tries to create a new test result for submitted/canceled with missing property - additionalInformation")([CVSB-9010](https://jira.dvsacloud.uk/browse/CVSB-9010) closed.
 
 And removed a test type class not necessary in the BE suite:
1- @Ignore("Bad test design - requires maintenance for every change in taxonomy")
@Title("[CVSB-579](https://jira.dvsacloud.uk/browse/CVSB-579) / [CVSB-746](https://jira.dvsacloud.uk/browse/CVSB-746) - [CVSB-996](https://jira.dvsacloud.uk/browse/CVSB-996) / [CVSB-2391](https://jira.dvsacloud.uk/browse/CVSB-2391) AC1 - API Consumer retrieve all the test types and test codes reference data")
 

Still, some of the tests need to keep ignoring tags for further investigation if these tests may be caused duplication on AWS DynamoDB issues or not. We created another ticket for these remaining tests.

**Review by danielchildsbjss — DISMISSED** [review]

**Review by Ian-Hodges — DISMISSED** [review]

**Review by danielchildsbjss — APPROVED** [review]

**Review by IuliaDVSA — CHANGES_REQUESTED** [review]
Please remove In-test tags and associated imports

**Review by IuliaDVSA — APPROVED** [review]

**Review by danielchildsbjss — APPROVED** [review]

**Pull request merged**
